version: "3.9"
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  # Uncomment the below lines to add a simple db explorer at localhost:8080 with username postgres and password password
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db